name: filecodebox
services:
    filecodebox:
        restart: always
        ports:
            - 8060:12345     #左边的8060可以随意更改成服务器上没有用过的端口
        volumes:
            - ./data:/app/data
        container_name: filecodebox
        image: lanol/filecodebox:beta
